replicaCount: 2
image:
  repository: mbenadik/flaskapp
  pullPolicy: Always
  tag: latest
app:
  version: 2.0.8
egress: false
service:
  type: ClusterIP
  port: 5000
  targetPort: 5000 # This will be ignored if Ingress is used
storageClassName:
  name: local-path
labels:
  templated: "true"
db:
  name: mysql-db
  strategy: Recreate
  dbname: flaskappdb
  version: 5.7
env:
  - name: FLASK_VERSION
    value: default
  - name: VAULT_ADDR
    value: http://vault.vault.svc.cluster.local:8200
ingress:
  enabled: true
  className: localport
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts: []
  tls: []
resources: {}
serviceAccount:
  create: true
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
