replicaCount: 2

image:
  repository: mbenadik/flaskapp
  pullPolicy: Always
  tag: latest
app:
  version: 2.0.1
service:
  type: ClusterIP
  port: 5000
  targetPort: 5000  # This will be ignored if Ingress is used
storageClassName:
  name: local-path
db:
  name: mysql-db
  password: cm9vdA==
  user: root
  strategy: Recreate
  dbname: flaskappdb
  version: 5.7

env:
  - name: FLASK_VERSION
    value: default
ingress:
  enabled: true
  className: localport
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts: []
  tls: []

resources: {}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
