apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-crossservice-flask-{{ .Values.color }}
  namespace: default
spec:
  podSelector:
    matchLabels:
      flask-app: flask-app-{{ .Values.color }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {} 
    - to:
        - podSelector:
            matchLabels:
              flask-app: flask-app-{{ .Values.color }}
