apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}-deployment-{{ .Values.color }}
spec:
  selector:
    matchLabels:
      app: mysql
      color: {{ .Values.color }}
  strategy:
    type: {{ .Values.db.strategy }}
  template:
    metadata:
      labels:
        app: mysql
        color: {{ .Values.color }}
    spec:
      containers:
      - image: mysql:{{ .Values.db.version }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.name }}-secret-{{ .Values.color }}
              key: mysql-root-password
        ports:
        - containerPort: 3306
          name: {{ .Values.db.name }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.db.name }}-pvc-{{ .Values.color }}
      imagePullSecrets:
      - name: my-dockerhub-secret  # Reference the secret here
