apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.name }}-pvc
spec:
  storageClassName: {{ .Values.storageClassName.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
