replicaCount: 2

image:
  repository: mbenadik/flaskapp
  pullPolicy: Always
  tag: latest
labels:
  - name: app
    name: flask-app-blue
service:
  type: ClusterIP
  port: 5000
  targetPort: 5000  # This will be ignored if Ingress is used
color: blue
env:
  - name: FLASK_ENV
    value: prod
  - name: FLASK_COLOR
    value: blue
  - name: CROSSSERVICE_NAME
    value: flask-green-flaskapp-chart
  - name: RABBIT_MQ_HOST
    value: my-rabbitmq.rabbitmq.svc.cluster.local
  - name: RABBIT_MQ_PORT
    value: 5672
  - name: RABBITMQ_QUEUE
    value: green-queue

ingress:
  enabled: true
  className: localport
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: 192.168.56.108
      paths:
        - path: /blue(.*)
          pathType: ImplementationSpecific
        - path: /staticblue/(.*)
          pathType: ImplementationSpecific
  tls: []

resources: {}

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
